{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: admiral-demo-postgres-init
  labels:
    {{- include "admiral-demo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  init.sql: |
    -- Enable uuid-ossp extension in the default database
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    -- Create additional databases for demo services
    CREATE DATABASE keycloak;
    CREATE DATABASE temporal;
    CREATE DATABASE temporal_visibility;
{{- end }}
